name: tml
channels:
  - conda-forge
  - defaults
dependencies:
  - anndata=0.11.1
  - appnope=0.1.4
  - array-api-compat=1.9.1
  - asttokens=2.4.1
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - c-blosc2=2.12.0
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.0
  - freetype=2.12.1
  - get-annotations=0.1.2
  - h5py=3.12.1
  - hdf5=1.12.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.12
  - legacy-api-wrap=1.4.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libcxx=19.1.4
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.28
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.4.0
  - llvm-openmp=19.1.4
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numba=0.60.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyparsing=3.2.0
  - pytables=3.9.2
  - python=3.10.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - scanpy=1.10.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info=1.0.0
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - stdlib-list=0.11.0
  - tables=3.9.2
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - umap-learn=0.5.7
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - accumulation-tree==0.6.4
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - alembic==1.14.0
      - async-timeout==5.0.1
      - attrs==24.2.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorlog==6.9.0
      - datasets==3.1.0
      - dill==0.3.8
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - greenlet==3.1.1
      - grpcio==1.68.0
      - huggingface-hub==0.26.2
      - idna==3.10
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - loompy==3.0.7
      - mako==1.3.6
      - markdown==3.7
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - numpy-groupies==0.11.2
      - optuna==4.1.0
      - optuna-integration==4.1.0
      - peft==0.13.2
      - propcache==0.2.0
      - protobuf==5.28.3
      - pyarrow==18.0.0
      - pyudorandom==1.0.0
      - pyyaml==6.0.2
      - ray==2.39.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rpds-py==0.21.0
      - safetensors==0.4.5
      - sqlalchemy==2.0.36
      - sympy==1.13.3
      - tdigest==0.5.2.2
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.20.3
      - torch==2.2.2
      - transformers==4.46.3
      - urllib3==2.2.3
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.18.0
