defaults:
  - _self_
  - dataset: cell_x_gene
  - metadata: single_cell
  - prompt: cell_whisper_single_cell
  - llm: openai
  - model: mouseformer

exp:
  run_func: 
    _target_: experiment.train_clip

  seed: 42
  log_dir: # set during runtime to automatically created dir
  
  model: gpt-4o-mini # o1-mini 
  temperature: 0.7
  top_k_genes: 10

wandb:
  project: sc-rna
  entity:
  tags: